namespace be.Shared;

public record Episode(
    string Id,
    TitleType Type,
    string Name,
    int? Year,
    string ImageUrl,
    int? EndYear,
    DateTime? ReleaseDate,
    string Plot,
    string[] Genres,
    string? TrailerUrl,
    string Classification,
    Ratings Ratings,
    PersonSummary[] Cast,
    PersonSummary[] Directors,
    PersonSummary[] Writers,
    int SeasonNumber,
    int EpisodeNumber)
: Title(
    Id,
    Type,
    Name,
    Year,
    ImageUrl,
    EndYear,
    ReleaseDate,
    Plot,
    Genres,
    TrailerUrl,
    Classification,
    Ratings,
    Cast,
    Directors,
    Writers);
